{{- if .Values.huggingfaceHubToken.existingSecret }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.huggingfaceHubToken.existingSecret ) }}
{{- else }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-%s" .Release.Name "huggingface-hub-token")) }}
{{- if not $existingSecret }}
{{- $huggingfaceHubToken := randAlphaNum 32 | b64enc | quote }}
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-huggingface-hub-token
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  huggingface-hub-token: {{ $huggingfaceHubToken }}
---
{{- end }}
{{- end }}